Delivered-To: sitestgmai@gmail.com
Received: by 10.25.6.4 with SMTP id 4csp73339lfg;
        Fri, 19 Sep 2014 03:44:07 -0700 (PDT)
Return-Path: <d.pochernin@gmail.com>
Received-SPF: pass (google.com: domain of d.pochernin@gmail.com designates 10.140.40.84 as permitted sender) client-ip=10.140.40.84
Authentication-Results: mr.google.com;
       spf=pass (google.com: domain of d.pochernin@gmail.com designates 10.140.40.84 as permitted sender) smtp.mail=d.pochernin@gmail.com;
       dkim=pass header.i=@gmail.com
X-Received: from mr.google.com ([10.140.40.84])
        by 10.140.40.84 with SMTP id w78mr6956552qgw.87.1411123446540 (num_hops = 1);
        Fri, 19 Sep 2014 03:44:06 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=mime-version:date:message-id:subject:from:to:content-type;
        bh=mcIzZVFXaKw2R2LPRXSESYoYGhi9WaoVH9I+JflWsmw=;
        b=ALI7hSDHyTp3ihx7PSrkjRz1wC3L8jfU1kBKp7tqxs6AmwJTj7fi8So7A4wlL2J/nG
         Q8QTgzJjXkZLOZB8Tm5CPUc378UAFmpCwzbGCJb0W8sfsUe3WxZcI3X690dUhOVf99bB
         +vNFBcBmjrAmvkEoFiP4T9mFnv3DggE/ZOD3hnmFoXdlkFuV2kV5tj7AjoQgNJ2C2Prw
         KvUCfwGwlPdGulGr3WdAa6MP8Xj74AmpRM0LeNzSWGtH/GZwnkIWKm3gv4FIPn3Wqhyo
         eYisEC9cLmXuL3ws84Ble2fxyIkVp5zDsfU6bgZlluDy0Ov5q42XnBgh+OD7IboL1r7V
         2ylg==
MIME-Version: 1.0
X-Received: by 10.140.40.84 with SMTP id w78mr6956552qgw.87.1411123446526;
 Fri, 19 Sep 2014 03:44:06 -0700 (PDT)
Received: by 10.140.235.141 with HTTP; Fri, 19 Sep 2014 03:44:06 -0700 (PDT)
Date: Fri, 19 Sep 2014 13:44:06 +0300
Message-ID: <CAGipFedJSsB3Bd44MCTLK12P1cC8tU_v04Q+iWsXEPWm0DeViw@mail.gmail.com>
Subject: test1_in
From: =?UTF-8?B?0JTQvNC40YLRgNC40Lkg0J/QvtGH0LXRgNC90LjQvQ==?= <d.pochernin@gmail.com>
To: sitestgmai@gmail.com
Content-Type: multipart/mixed; boundary=001a11c122bac3dd55050368c7d0

--001a11c122bac3dd55050368c7d0
Content-Type: multipart/alternative; boundary=001a11c122bac3dd4f050368c7ce

--001a11c122bac3dd4f050368c7ce
Content-Type: text/plain; charset=UTF-8



--001a11c122bac3dd4f050368c7ce
Content-Type: text/html; charset=UTF-8

<div dir="ltr"><br></div>

--001a11c122bac3dd4f050368c7ce--

--001a11c122bac3dd55050368c7d0
Content-Type: text/plain; charset=US-ASCII; name="test1.txt"
Content-Disposition: attachment; filename="test1.txt"
Content-Transfer-Encoding: base64
X-Attachment-Id: f_i09eg65q0

dGVzdDEgdGVzdDIgdGVzdDM=
--001a11c122bac3dd55050368c7d0--

